Test_E-Commerce/config/routes.rb
require './app/store'
Depot::Application.routes.draw do
  resources :sellers

  resources :buyers

  match 'catalog' => StoreApp.new, via: :all
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  get "sessions/create"
  get "sessions/destroy"

  resources :users
  resources :products do
    get :who_bought, on: :member
  end

  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store', via: :all
  
end

Test_E-Commerce/app/models/buyer.rb
class Buyer < User
	has_one :cart
end

Test_E-Commerce/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :buyer

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
      current_item.price = current_item.product.price
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

Test_E-Commerce/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

Test_E-Commerce/app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

Test_E-Commerce/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  #...

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
# 
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :title, length: {minimum: 10}

  def self.latest
    Product.order(:updated_at).last
  end

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

Test_E-Commerce/app/models/seller.rb
class Seller < User
end

Test_E-Commerce/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end     
end

Test_E-Commerce/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

Test_E-Commerce/app/helpers/admin_helper.rb
module AdminHelper
end

Test_E-Commerce/app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

Test_E-Commerce/app/helpers/buyers_helper.rb
module BuyersHelper
end

Test_E-Commerce/app/helpers/carts_helper.rb
module CartsHelper
end

Test_E-Commerce/app/helpers/line_items_helper.rb
module LineItemsHelper
end

Test_E-Commerce/app/helpers/orders_helper.rb
module OrdersHelper
end

Test_E-Commerce/app/helpers/products_helper.rb
module ProductsHelper
end

Test_E-Commerce/app/helpers/sellers_helper.rb
module SellersHelper
end

Test_E-Commerce/app/helpers/sessions_helper.rb
module SessionsHelper
end

Test_E-Commerce/app/helpers/store_helper.rb
module StoreHelper
end

Test_E-Commerce/app/helpers/user_factory_helper.rb
module UserFactoryHelper
end

Test_E-Commerce/app/helpers/users_helper.rb
module UsersHelper
end

Test_E-Commerce/app/views/admin/index.html.erb
<h1>Welcome</h1>

It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

Test_E-Commerce/app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>E Commerce system</title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START:i18n -->
  <div id="banner">
<!-- START_HIGHLIGHT -->
  
<!-- END_HIGHLIGHT -->
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
<!-- END:i18n -->
  <div id="columns">
    <div id="side">
      <!-- START:hidden_div -->
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
    <!-- END:hidden_div -->

      <ul>
        <li><a href="/"><%= t('.home') %></a></li>
        <li><a href="/faq"><%= t('.questions') %></a></li>
        <li><a href="/news"><%= t('.news') %></a></li>
        <li><a href="/contact"><%= t('.contact') %></a></li>
      </ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete   %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>

Test_E-Commerce/app/views/order_notifier/received.text.erb
Dear <%= @order.name %>

Thank you for your order.

You ordered the following items:

<%= render @order.line_items -%>

We'll send you a separate e-mail when your order ships.

Test_E-Commerce/app/views/order_notifier/shipped.html.erb
<h3>Order Shipped</h3>
<p>
  This is just to let you know that we've shipped your recent order:
</p>

<table>
  <tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

Test_E-Commerce/app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/app/views/order_notifier/shipped.text.erb